# Generated by Django 4.1.2 on 2024-09-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('device_location', models.CharField(blank=True, default='Not Set', max_length=255, null=True)),
                ('time_on', models.DateTimeField(blank=True, null=True)),
                ('time_off', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_consumed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('device_location', models.CharField(blank=True, default='Not Set', max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_consumed', models.DateTimeField(blank=True, null=True)),
                ('is_standby', models.BooleanField(default=False)),
                ('is_consumed', models.BooleanField(default=False)),
            ],
        ),
    ]
